### ISSUE TITLE
Error at launch :/

### ISSUE THREAD

**Issue by Lajull-fr** [barbarbar338/reaction-role-example#1]
Hello, thx for your sharing code.

I have an issu at launch:
```
D:\Bot\reaction-role-example-main\node_modules\reaction-role\dist\index.js:48
            const adapter = new bookman_1.adapters.MongoDB({
                                                   ^

TypeError: Cannot read property 'MongoDB' of undefined
    at new ReactionRole (D:\Bot\reaction-role-example-main\node_modules\reaction-role\dist\index.js:48:52)
    at Object.<anonymous> (D:\Bot\reaction-role-example-main\index.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...
```

I have filled in the fields in .env
Hve you an idea ?

**Comment by thearkxd** [comment]
Can i see your code?

**Comment by Lajull-fr** [comment]
My bad i only use npm i but note yarn :/
I see yarn or npm i
It work with yarn, sorry

**Comment by barbarbar338** [comment]
Actually it's not your fault i just updated package and not example
i'll update it soon
